### ISSUE TITLE
H4CF conversion problem

### ISSUE THREAD

**Issue by sr-murthy** [hdfeos/docker-h4cf#3]
The H4CF conversion utility `h4tonccf` in the Docker container does not work.

    /usr/local/bin/h4tonccf: error while loading shared libraries: libnetcdf.so.11: cannot open shared object file: No such file or directory

**Comment by sr-murthy** [comment]
This file is in `/usr/local/lib`, which is exported via the `LDFLAGS` env. variable before the NetCDF4 build. It might be that `LD_LIBRARY_PATH` may need to be set as well.

**Comment by hdfeos** [comment]
Yes, setting the library path is necessary to make /usr/local/bin/h4tonccf work.
``
$export LD_LIBRARY_PATH=/usr/local/lib
``
